# Generated by Django 5.0.6 on 2024-06-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price2',
            field=models.IntegerField(default=0),
        ),
    ]
