# Generated by Django 5.0.6 on 2024-06-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_price2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price2',
        ),
    ]
